bugfix: Fix issues when error cursor is returned
The error in dev:
```
2026-09-22 17:44:34,771 ERROR s.server.service.JobScheduler:56  - Job discover-maven-namespaces failed
java.lang.RuntimeException: missing nexus.index.chain-id
	at scala.sys.package$.error(package.scala:29)
	at scaladex.infra.MavenCentralIndexClientImpl.$anonfun$4(MavenCentralIndexClientImpl.scala:47)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:273)
	at scaladex.infra.MavenCentralIndexClientImpl.fetchRemoteCursor$$anonfun$1$$anonfun$1(MavenCentralIndexClientImpl.scala:47)
	at scala.util.Success.map(Try.scala:302)
	at scala.concurrent.Future.map$$anonfun$1(Future.scala:261)
	at org.apache.pekko.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:93)
	at scala.concurrent.Future.map$(Future.scala:261)
	at org.apache.pekko.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:85)
	at scaladex.infra.MavenCentralIndexClientImpl.fetchRemoteCursor$$anonfun$1(MavenCentralIndexClientImpl.scala:52)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:525)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:72)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$1(BatchingExecutor.scala:109)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$adapted$1(BatchingExecutor.scala:118)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:101)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:118)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:86)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```